export const PRODUCT_RESULT_SUCCESS = 'PRODUCT_RESULT_SUCCESS';
export const GET_USER = 'GET_USER';
export const POST_USER = 'POST_USER';
export const POST_PRODUCT_SUCCESS= 'POST_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS= 'DELETE_PRODUCT_SUCCESS';
export const PRODUCT_RESULT_ERROR='PRODUCT_RESULT_ERROR';